name: "Github Action Weather Bot"

on:
  push:
  schedule:
    -cron: "0 21 * * *"

jobs: 
  bot:
    runs-on: ubuntu-latest
    steps:
      -name: "Checkout Master Branch"
        uses: actions/checkout@v1
      -name: "Install Node"
        uses: actions/setup-node@v1
      -name: 'Install NPM Dependencies'
        run: npm install
      -name: 'Run Code'
        run: node index.js
        env: 
          WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN}}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK}}